"""
Markdown report generation.

Creates Markdown summaries for course materials and activities.
"""

from pathlib import Path
from datetime import datetime
from typing import Optional

from core.config import Config, get_config
from core.classroom_api import CourseMaterial, CourseWork, Course


class MarkdownWriter:
    """
    Generates Markdown reports for Google Classroom content.

    Creates readable Markdown files for materials and coursework.
    """

    def __init__(self, config: Optional[Config] = None):
        """
        Initialize Markdown writer.

        Args:
            config: Configuration instance
        """
        self.config = config or get_config()

    def generate_material_summary(
        self,
        material: CourseMaterial,
        course: Course,
        analysis: str = "",
        summary: str = "",
        key_topics: list[str] = None,
        output_path: Optional[Path] = None,
    ) -> Path:
        """
        Generate a Markdown summary for a course material.

        Args:
            material: The CourseMaterial to summarize
            course: The parent Course
            analysis: AI-generated analysis text
            summary: Summary of the material
            key_topics: List of key topics/concepts
            output_path: Optional custom output path

        Returns:
            Path to generated Markdown file
        """
        if output_path is None:
            safe_title = "".join(
                c if c.isalnum() or c in " -_" else "_"
                for c in material.title
            )[:50]
            filename = f"summary_{safe_title}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
            output_path = self.config.reports_dir / filename

        output_path.parent.mkdir(parents=True, exist_ok=True)

        lines = []

        # Header
        lines.append(f"# {material.title}")
        lines.append("")

        # Metadata
        lines.append(f"**Course**: {course.name}")
        if course.section:
            lines.append(f"**Section**: {course.section}")
        if material.creation_time:
            lines.append(f"**Created**: {material.creation_time[:10]}")
        lines.append("")

        # Description
        if material.description:
            lines.append("## Description")
            lines.append("")
            lines.append(material.description)
            lines.append("")

        # Summary
        if summary:
            lines.append("## Summary")
            lines.append("")
            lines.append(summary)
            lines.append("")

        # Key Topics
        if key_topics:
            lines.append("## Key Topics")
            lines.append("")
            for topic in key_topics:
                lines.append(f"- {topic}")
            lines.append("")

        # Analysis
        if analysis:
            lines.append("## Analysis")
            lines.append("")
            lines.append(analysis)
            lines.append("")

        # Attached Resources
        if material.materials:
            lines.append("## Attached Resources")
            lines.append("")
            for mat in material.materials:
                mat_type = mat.type.replace("_", " ").title()
                title = mat.title or "Untitled"
                if mat.url:
                    lines.append(f"- **{mat_type}**: [{title}]({mat.url})")
                else:
                    lines.append(f"- **{mat_type}**: {title}")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append(f"*Generated by Hintly on {datetime.now().strftime('%Y-%m-%d %H:%M')}*")

        # Write file
        output_path.write_text("\n".join(lines))

        return output_path

    def generate_coursework_summary(
        self,
        coursework: CourseWork,
        course: Course,
        summary: str = "",
        key_points: list[str] = None,
        output_path: Optional[Path] = None,
    ) -> Path:
        """
        Generate a Markdown summary for coursework.

        Args:
            coursework: The CourseWork to summarize
            course: The parent Course
            summary: Summary text
            key_points: Key points about the coursework
            output_path: Optional custom output path

        Returns:
            Path to generated Markdown file
        """
        if output_path is None:
            safe_title = "".join(
                c if c.isalnum() or c in " -_" else "_"
                for c in coursework.title
            )[:50]
            filename = f"coursework_{safe_title}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
            output_path = self.config.reports_dir / filename

        output_path.parent.mkdir(parents=True, exist_ok=True)

        lines = []

        # Header
        lines.append(f"# {coursework.title}")
        lines.append("")

        # Metadata
        lines.append(f"**Course**: {course.name}")
        lines.append(f"**Type**: {coursework.work_type.replace('_', ' ').title()}")
        if coursework.max_points:
            lines.append(f"**Points**: {coursework.max_points}")
        if coursework.due_date:
            due = coursework.due_date
            if coursework.due_time:
                due += f" at {coursework.due_time}"
            lines.append(f"**Due**: {due}")
        lines.append("")

        # Description
        if coursework.description:
            lines.append("## Description")
            lines.append("")
            lines.append(coursework.description)
            lines.append("")

        # Summary
        if summary:
            lines.append("## Summary")
            lines.append("")
            lines.append(summary)
            lines.append("")

        # Key Points
        if key_points:
            lines.append("## Key Points")
            lines.append("")
            for point in key_points:
                lines.append(f"- {point}")
            lines.append("")

        # Attached Materials
        if coursework.materials:
            lines.append("## Attached Materials")
            lines.append("")
            for mat in coursework.materials:
                mat_type = mat.type.replace("_", " ").title()
                title = mat.title or "Untitled"
                if mat.url:
                    lines.append(f"- **{mat_type}**: [{title}]({mat.url})")
                else:
                    lines.append(f"- **{mat_type}**: {title}")
            lines.append("")

        # Link
        if coursework.alternate_link:
            lines.append("## Links")
            lines.append("")
            lines.append(f"- [View in Classroom]({coursework.alternate_link})")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append(f"*Generated by Hintly on {datetime.now().strftime('%Y-%m-%d %H:%M')}*")

        output_path.write_text("\n".join(lines))

        return output_path

    def generate_course_overview(
        self,
        course: Course,
        coursework: list[CourseWork] = None,
        materials: list[CourseMaterial] = None,
        summary: str = "",
        output_path: Optional[Path] = None,
    ) -> Path:
        """
        Generate a Markdown overview of a course.

        Args:
            course: The Course to overview
            coursework: List of coursework items
            materials: List of materials
            summary: Course summary
            output_path: Optional custom output path

        Returns:
            Path to generated Markdown file
        """
        if output_path is None:
            safe_name = "".join(
                c if c.isalnum() or c in " -_" else "_"
                for c in course.name
            )[:50]
            filename = f"course_{safe_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
            output_path = self.config.reports_dir / filename

        output_path.parent.mkdir(parents=True, exist_ok=True)

        lines = []

        # Header
        lines.append(f"# {course.name}")
        lines.append("")

        if course.section:
            lines.append(f"**Section**: {course.section}")
        lines.append(f"**State**: {course.state}")
        lines.append("")

        # Description
        if course.description:
            lines.append("## Description")
            lines.append("")
            lines.append(course.description)
            lines.append("")

        # Summary
        if summary:
            lines.append("## Summary")
            lines.append("")
            lines.append(summary)
            lines.append("")

        # Coursework
        if coursework:
            lines.append("## Coursework")
            lines.append("")
            lines.append("| Title | Type | Due Date | Points |")
            lines.append("|-------|------|----------|--------|")
            for cw in coursework:
                cw_type = cw.work_type.replace("_", " ").title()
                due = cw.due_date or "N/A"
                points = str(cw.max_points) if cw.max_points else "N/A"
                lines.append(f"| {cw.title} | {cw_type} | {due} | {points} |")
            lines.append("")

        # Materials
        if materials:
            lines.append("## Materials")
            lines.append("")
            for mat in materials:
                lines.append(f"- **{mat.title}**")
                if mat.description:
                    lines.append(f"  - {mat.description[:100]}...")
            lines.append("")

        # Links
        if course.alternate_link:
            lines.append("## Links")
            lines.append("")
            lines.append(f"- [View in Classroom]({course.alternate_link})")
            lines.append("")

        # Footer
        lines.append("---")
        lines.append(f"*Generated by Hintly on {datetime.now().strftime('%Y-%m-%d %H:%M')}*")

        output_path.write_text("\n".join(lines))

        return output_path
